name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to DigitalOcean
      run: |
        ssh root@${{ secrets.DROPLET_IP }} << 'EOF'
        mkdir -p /var/www/html/ProyectoTest
        if [ ! -d "/var/www/html/ProyectoTest/.git" ]; then
          git clone https://github.com/Percy-developer/TerraDigital.git /var/www/html/ProyectoTest;
        else
          cd /var/www/html/ProyectoTest && git pull origin main;
        fi
        EOF
